In [1]:
import pandas as pd
from Load_from_postgres import load_data

ModuleNotFoundError: No module named 'Load_from_postgres'

In [2]:


# Load data from PostgreSQL
data = load_data()

# Check if data was loaded successfully
if data is not None:
    print("Data loaded successfully!")
    print(data.head())  # Display the first few rows of the DataFrame
else:
    print("Failed to load data.")

Data loaded successfully!
      Bearer Id            Start  Start ms              End  End ms  \
0  1.311448e+19   4/4/2019 12:01     770.0  4/25/2019 14:35   662.0
1  1.311448e+19   4/9/2019 13:04     235.0   4/25/2019 8:15   606.0
2  1.311448e+19   4/9/2019 17:42       1.0  4/25/2019 11:58   652.0
3  1.311448e+19   4/10/2019 0:31     486.0   4/25/2019 7:36   171.0
4  1.311448e+19  4/12/2019 20:10     565.0  4/25/2019 10:40   954.0

   Dur. (ms)          IMSI  MSISDN/Number          IMEI  \
0  1823652.0  2.082014e+14   3.366496e+10  3.552121e+13
1  1365104.0  2.082019e+14   3.368185e+10  3.579401e+13
2  1361762.0  2.082003e+14   3.376063e+10  3.528151e+13
3  1321509.0  2.082014e+14   3.375034e+10  3.535661e+13
4  1089009.0  2.082014e+14   3.369980e+10  3.540701e+13

      Last Location Name  ...  Youtube DL (Bytes)  Youtube UL (Bytes)  \
0  9.16456699548519E+015  ...          15854611.0           2501332.0
1                L77566A  ...          20247395.0          19111729.0
2                D42335A  ...          19725661.0          14699576.0
3                T21824A  ...          21388122.0          15146643.0
4                D88865A  ...          15259380.0          18962873.0

   Netflix DL (Bytes)  Netflix UL (Bytes)  Gaming DL (Bytes)  \
0           8198936.0           9656251.0        278082303.0
1          18338413.0          17227132.0        608750074.0
2          17587794.0           6163408.0        229584621.0
3          13994646.0           1097942.0        799538153.0
4          17124581.0            415218.0        527707248.0

   Gaming UL (Bytes)  Other DL (Bytes)  Other UL (Bytes)  Total UL (Bytes)  \
0         14344150.0       171744450.0         8814393.0        36749741.0
1          1170709.0       526904238.0        15055145.0        53800391.0
2           395630.0       410692588.0         4215763.0        27883638.0
3         10849722.0       749039933.0        12797283.0        43324218.0
4          3529801.0       550709500.0        13910322.0        38542814.0

   Total DL (Bytes)
0       308879636.0
1       653384965.0
2       279807335.0
3       846028530.0
4       569138589.0

[5 rows x 55 columns]

In [3]:
import os
print(os.listdir())

['Load_from_postgres.py', 'README.md', 'Task1.ipynb', 'test_import.py', '__init__.py', '__pycache__']

In [4]:
# Display summary statistics
print(data.describe())

          Bearer Id       Start ms         End ms     Dur. (ms)          IMSI  \
count  1.490100e+05  150000.000000  150000.000000  1.500000e+05  1.494310e+05
mean   1.013887e+19     499.188200     498.800880  1.046086e+05  2.082016e+14
std    2.893173e+18     288.611834     288.097653  8.103762e+04  2.148809e+10
min    6.917538e+18       0.000000       0.000000  7.142000e+03  2.040471e+14
25%    7.349883e+18     250.000000     251.000000  5.744050e+04  2.082014e+14
50%    7.349883e+18     499.000000     500.000000  8.639900e+04  2.082015e+14
75%    1.304243e+19     749.000000     750.000000  1.324302e+05  2.082018e+14
max    1.318654e+19     999.000000     999.000000  1.859336e+06  2.140743e+14

       MSISDN/Number          IMEI  Avg RTT DL (ms)  Avg RTT UL (ms)  \
count   1.489350e+05  1.494290e+05    122172.000000    122189.000000
mean    4.188282e+10  4.847455e+13       109.795706        17.662883
std     2.447443e+12  2.241637e+13       619.782739        84.793524
min     3.360100e+10  4.400152e+11         0.000000         0.000000
25%     3.365130e+10  3.546071e+13        32.000000         2.000000
50%     3.366371e+10  3.572201e+13        45.000000         5.000000
75%     3.368349e+10  8.611970e+13        70.000000        15.000000
max     8.823971e+14  9.900120e+13     96923.000000      7120.000000

       Avg Bearer TP DL (kbps)  ...  Youtube DL (Bytes)  Youtube UL (Bytes)  \
count            150000.000000  ...        1.500010e+05        1.500010e+05
mean              13300.045927  ...        1.163407e+07        1.100941e+07
std               23971.878541  ...        6.710569e+06        6.345423e+06
min                   0.000000  ...        5.300000e+01        1.050000e+02
25%                  43.000000  ...        5.833501e+06        5.517965e+06
50%                  63.000000  ...        1.161602e+07        1.101345e+07
75%               19710.750000  ...        1.744852e+07        1.651556e+07
max              378160.000000  ...        2.325910e+07        2.201196e+07

       Netflix DL (Bytes)  Netflix UL (Bytes)  Gaming DL (Bytes)  \
count        1.500010e+05        1.500010e+05       1.500010e+05
mean         1.162685e+07        1.100175e+07       4.220447e+08
std          6.725218e+06        6.359490e+06       2.439675e+08
min          4.200000e+01        3.500000e+01       2.516000e+03
25%          5.777156e+06        5.475981e+06       2.104733e+08
50%          1.164222e+07        1.099638e+07       4.234081e+08
75%          1.747048e+07        1.650727e+07       6.331742e+08
max          2.325919e+07        2.201196e+07       8.434419e+08

       Gaming UL (Bytes)  Other DL (Bytes)  Other UL (Bytes)  \
count       1.500010e+05      1.500010e+05      1.500010e+05
mean        8.288398e+06      4.211005e+08      8.264799e+06
std         4.782700e+06      2.432050e+08      4.769004e+06
min         5.900000e+01      3.290000e+03      1.480000e+02
25%         4.128476e+06      2.101869e+08      4.145943e+06
50%         8.291208e+06      4.218030e+08      8.267071e+06
75%         1.243162e+07      6.316918e+08      1.238415e+07
max         1.655879e+07      8.434425e+08      1.655882e+07

       Total UL (Bytes)  Total DL (Bytes)
count      1.500000e+05      1.500000e+05
mean       4.112121e+07      4.546434e+08
std        1.127639e+07      2.441429e+08
min        2.866892e+06      7.114041e+06
25%        3.322201e+07      2.431068e+08
50%        4.114331e+07      4.558411e+08
75%        4.903424e+07      6.657055e+08
max        7.833131e+07      9.029696e+08

[8 rows x 50 columns]

In [5]:
print(data.isnull().sum())

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [7]:
data.shape

(150001, 55)

## Handling Missing Data

In [8]:
data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

 Fill numeric columns with the mean and Fill non-numeric columns with the mode

In [9]:
def fill_missing_values(Data):
    for column in data.columns:
        if pd.api.types.is_numeric_dtype(data[column]):
            # Fill numeric columns with the mean
            mean_value = data[column].mean()
            data[column].fillna(mean_value, inplace=True)
        else:
            # Fill non-numeric columns with the mode
            mode_value = data[column].mode()[0]  # Get the first mode
            data[column].fillna(mode_value, inplace=True)

# Apply the function
fill_missing_values(data)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15368\724285368.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(mean_value, inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_15368\724285368.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(mode_value, inplace=True)

In [10]:
data.isnull().sum()

Bearer Id                                   0
Start                                       0
Start ms                                    0
End                                         0
End ms                                      0
Dur. (ms)                                   0
IMSI                                        0
MSISDN/Number                               0
IMEI                                        0
Last Location Name                          0
Avg RTT DL (ms)                             0
Avg RTT UL (ms)                             0
Avg Bearer TP DL (kbps)                     0
Avg Bearer TP UL (kbps)                     0
TCP DL Retrans. Vol (Bytes)                 0
TCP UL Retrans. Vol (Bytes)                 0
DL TP < 50 Kbps (%)                         0
50 Kbps < DL TP < 250 Kbps (%)              0
250 Kbps < DL TP < 1 Mbps (%)               0
DL TP > 1 Mbps (%)                          0
UL TP < 10 Kbps (%)                         0
10 Kbps < UL TP < 50 Kbps (%)               0
50 Kbps < UL TP < 300 Kbps (%)              0
UL TP > 300 Kbps (%)                        0
HTTP DL (Bytes)                             0
HTTP UL (Bytes)                             0
Activity Duration DL (ms)                   0
Activity Duration UL (ms)                   0
Dur. (ms).1                                 0
Handset Manufacturer                        0
Handset Type                                0
Nb of sec with 125000B < Vol DL             0
Nb of sec with 1250B < Vol UL < 6250B       0
Nb of sec with 31250B < Vol DL < 125000B    0
Nb of sec with 37500B < Vol UL              0
Nb of sec with 6250B < Vol DL < 31250B      0
Nb of sec with 6250B < Vol UL < 37500B      0
Nb of sec with Vol DL < 6250B               0
Nb of sec with Vol UL < 1250B               0
Social Media DL (Bytes)                     0
Social Media UL (Bytes)                     0
Google DL (Bytes)                           0
Google UL (Bytes)                           0
Email DL (Bytes)                            0
Email UL (Bytes)                            0
Youtube DL (Bytes)                          0
Youtube UL (Bytes)                          0
Netflix DL (Bytes)                          0
Netflix UL (Bytes)                          0
Gaming DL (Bytes)                           0
Gaming UL (Bytes)                           0
Other DL (Bytes)                            0
Other UL (Bytes)                            0
Total UL (Bytes)                            0
Total DL (Bytes)                            0
dtype: int64

In [11]:
data.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

### Identifying the top 10 handsets used by the customers.

In [12]:
top_10_handsets = data['Handset Type'].value_counts().head(10)
print(top_10_handsets)

Handset Type
Huawei B528S-23A                20324
Apple iPhone 6S (A1688)          9419
Apple iPhone 6 (A1586)           9023
undefined                        8987
Apple iPhone 7 (A1778)           6326
Apple iPhone Se (A1723)          5187
Apple iPhone 8 (A1905)           4993
Apple iPhone Xr (A2105)          4568
Samsung Galaxy S8 (Sm-G950F)     4520
Apple iPhone X (A1901)           3813
Name: count, dtype: int64

### The top 3 handset manufacturers

In [13]:
top_3_handsets_man = data['Handset Manufacturer'].value_counts().head(3)
print(top_3_handsets_man)

Handset Manufacturer
Apple      60137
Samsung    40839
Huawei     34423
Name: count, dtype: int64

### Identifying the top 5 handsets per top 3 handset manufacturer

In [14]:
# Filter by each of the top 3 manufacturers and find the top 5 handsets
for manufacturer in top_3_handsets_man.index:
    top_5_handsets = data[data['Handset Manufacturer'] == manufacturer]['Handset Type'].value_counts().head(5)
    print(f"Top 5 handsets for {manufacturer} :",top_5_handsets)

Top 5 handsets for Apple : Handset Type
Apple iPhone 6S (A1688)    9419
Apple iPhone 6 (A1586)     9023
Apple iPhone 7 (A1778)     6326
Apple iPhone Se (A1723)    5187
Apple iPhone 8 (A1905)     4993
Name: count, dtype: int64
Top 5 handsets for Samsung : Handset Type
Samsung Galaxy S8 (Sm-G950F)    4520
Samsung Galaxy A5 Sm-A520F      3724
Samsung Galaxy J5 (Sm-J530)     3696
Samsung Galaxy J3 (Sm-J330)     3484
Samsung Galaxy S7 (Sm-G930X)    3199
Name: count, dtype: int64
Top 5 handsets for Huawei : Handset Type
Huawei B528S-23A                  19752
Huawei E5180                       2079
Huawei P20 Lite Huawei Nova 3E     2021
Huawei P20                         1480
Huawei Y6 2018                      997
Name: count, dtype: int64

### Task 1.1

In [15]:
data.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

In [16]:
aggregated_data = data.groupby('IMSI').agg(
    number_of_sessions=('IMSI', 'count'),
    total_session_duration=('Dur. (ms)', 'sum'),
    total_download_data_bytes=('HTTP DL (Bytes)', 'sum'),
    total_social_media_download_bytes=('Social Media DL (Bytes)', 'sum'),
    total_upload_data_bytes=('HTTP UL (Bytes)', 'sum'),
    total_social_media_upload_bytes=('Social Media UL (Bytes)', 'sum'),
).reset_index()

In [17]:

# Calculate total download and upload data
aggregated_data['total_download_data_bytes'] = (
    aggregated_data['total_download_data_bytes'] + 
    aggregated_data['total_social_media_download_bytes']
)
aggregated_data['total_upload_data_bytes'] = (
    aggregated_data['total_upload_data_bytes'] + 
    aggregated_data['total_social_media_upload_bytes']
)

In [18]:
# Drop intermediate columns if not needed
# aggregated_data.drop(columns=['total_social_media_download_bytes', 'total_social_media_upload_bytes'], inplace=True)

aggregated_data.head()

,IMSI,number_of_sessions,total_session_duration,total_download_data_bytes,total_social_media_download_bytes,total_upload_data_bytes,total_social_media_upload_bytes
0,2.040471e+14,1,869844.0,1.159712e+08,1500145.0,3.288244e+06,45943.0
1,2.040808e+14,1,877385.0,1.151396e+08,668596.0,3.288929e+06,46628.0
2,2.082001e+14,1,86019.0,3.074099e+06,3073697.0,4.953700e+04,49084.0
3,2.082001e+14,1,86254.0,3.269398e+06,2542767.0,2.030320e+05,34337.0
4,2.082001e+14,2,573923.0,2.322689e+08,3326811.0,6.584508e+06,99905.0

In [30]:
data.columns = data.columns.str.strip()

# Aggregation per user (MSISDN/Number)
user_aggregation = data.groupby('MSISDN/Number').agg({
    'Bearer Id': 'count',  # Number of xDR sessions
    'Dur. (ms)': 'sum',  # Total session duration (in milliseconds)
    'Total DL (Bytes)': 'sum',  # Total download data
    'Total UL (Bytes)': 'sum',  # Total upload data
    'Social Media DL (Bytes)': 'sum',
    'Social Media UL (Bytes)': 'sum',
    'Google DL (Bytes)': 'sum',
    'Google UL (Bytes)': 'sum',
    'Email DL (Bytes)': 'sum',
    'Email UL (Bytes)': 'sum',
    'Youtube DL (Bytes)': 'sum',
    'Youtube UL (Bytes)': 'sum',
    'Netflix DL (Bytes)': 'sum',
    'Netflix UL (Bytes)': 'sum',
    'Gaming DL (Bytes)': 'sum',
    'Gaming UL (Bytes)': 'sum',
    'Other DL (Bytes)': 'sum',
    'Other UL (Bytes)': 'sum'
}).reset_index()

user_aggregation.head()

,MSISDN/Number,Bearer Id,Dur. (ms),Total DL (Bytes),Total UL (Bytes),Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes)
0,3.360100e+10,1,116720.0,8.426375e+08,36053108.0,2206504.0,25631.0,3337123.0,1051882.0,837400.0,493962.0,14900201.0,6724347.0,10265105.0,16915876.0,8.110911e+08,1367528.0,377096990.0,9473882.0
1,3.360100e+10,1,181230.0,1.207552e+08,36104459.0,2598548.0,62017.0,4197697.0,1137166.0,2828821.0,478960.0,5324251.0,7107972.0,770569.0,10451194.0,1.050353e+08,14714780.0,279557701.0,2152370.0
2,3.360100e+10,1,134969.0,5.566597e+08,39306820.0,3148004.0,47619.0,3343483.0,99643.0,2436500.0,768880.0,2137272.0,19196298.0,16525919.0,2827981.0,5.290685e+08,9759228.0,495086501.0,6607171.0
3,3.360101e+10,1,49878.0,4.019932e+08,20327526.0,251469.0,28825.0,5937765.0,3740728.0,2178618.0,106052.0,4393123.0,2584198.0,1157362.0,784730.0,3.880748e+08,3051292.0,25248001.0,10031701.0
4,3.360101e+10,2,37104.0,1.363130e+09,94280527.0,2861230.0,51312.0,13728668.0,4770948.0,2247808.0,1057661.0,10339971.0,31193031.0,24971647.0,24230077.0,1.308981e+09,5816727.0,777643713.0,27160771.0

### Task 1.2 - Exploratory Data Analysis (EDA)

In [20]:
### Handling the missing VAlue Already Done

In [26]:
data.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

In [39]:
# chckin Outliers 
from scipy import stats
import numpy as np
# Calculate Z-scores
numeric_cols = user_aggregation.select_dtypes(include=[np.number]).columns
z_scores = stats.zscore(user_aggregation[numeric_cols])
abs_z_scores = np.abs(z_scores)
user_aggregation_cleaned = user_aggregation[(abs_z_scores < 3).all(axis=1)]

### Variable Transformation

In [41]:
# Segment users into top five decile classes based on total session duration
user_aggregation_cleaned['Decile'] = pd.qcut(user_aggregation_cleaned['Dur. (ms)'], 10, labels=False)
decile_summary = user_aggregation_cleaned.groupby('Decile').agg({
    'Total DL (Bytes)': 'sum',
    'Total UL (Bytes)': 'sum'
})
decile_summary.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_15368\480346654.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_aggregation_cleaned['Decile'] = pd.qcut(user_aggregation_cleaned['Dur. (ms)'], 10, labels=False)

        Total DL (Bytes)  Total UL (Bytes)
Decile
0           4.966814e+12      4.471028e+11
1           5.563969e+12      5.024128e+11
2           5.955577e+12      5.404199e+11
3           5.633799e+12      5.092355e+11
4           4.589364e+12      4.152213e+11

In [42]:
# Basic Metrix

metrics_summary = user_aggregation_cleaned.describe()
metrics_summary

,MSISDN/Number,Bearer Id,Dur. (ms),Total DL (Bytes),Total UL (Bytes),Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Decile
count,1.063500e+05,106350.000000,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,106350.000000,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,1.063500e+05,106350.000000
mean,3.370392e+10,1.374424,1.383238e+05,6.248800e+08,5.651608e+07,2.468056e+06,45243.736192,7.902750e+06,2.826621e+06,2.462448e+06,6.422655e+05,1.598378e+07,1.513182e+07,1.598270e+07,1.511850e+07,5.800802e+08,1.139542e+07,5.787984e+08,1.135620e+07,4.484401
std,9.700247e+09,0.737988,1.159595e+05,4.392586e+08,3.304038e+07,1.792315e+06,32930.616448,5.743232e+06,2.064483e+06,1.796574e+06,4.692034e+05,1.167386e+07,1.099851e+07,1.170078e+07,1.100733e+07,4.210960e+08,8.296514e+06,4.216175e+08,8.256592e+06,2.877685
min,3.360100e+10,1.000000,7.142000e+03,8.827082e+06,2.866892e+06,1.200000e+01,0.000000,2.070000e+02,3.000000e+00,9.700000e+01,1.400000e+01,5.300000e+01,1.060000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.560000e+02,0.000000
25%,3.365088e+10,1.000000,7.068900e+04,3.135624e+08,3.634530e+07,1.171279e+06,21494.000000,3.788383e+06,1.335208e+06,1.179291e+06,3.052758e+05,7.620892e+06,7.213504e+06,7.560954e+06,7.175950e+06,2.781223e+08,5.419080e+06,2.754825e+08,5.439753e+06,2.000000
50%,3.366365e+10,1.000000,1.022085e+05,5.682598e+08,4.670289e+07,2.256678e+06,41374.000000,7.231898e+06,2.583696e+06,2.256602e+06,5.848105e+05,1.454689e+07,1.381318e+07,1.458666e+07,1.383050e+07,5.302810e+08,1.040840e+07,5.279244e+08,1.033932e+07,4.500000
75%,3.368345e+10,2.000000,1.727990e+05,8.042188e+08,6.511708e+07,3.255298e+06,59691.250000,1.039302e+07,3.730536e+06,3.239338e+06,8.492532e+05,2.104207e+07,1.989868e+07,2.105591e+07,1.993181e+07,7.641039e+08,1.502782e+07,7.623929e+08,1.497099e+07,7.000000
max,3.197021e+12,9.000000,1.015137e+06,4.765821e+09,3.481942e+08,1.878640e+07,339786.000000,5.740664e+07,2.237532e+07,1.722074e+07,5.297254e+06,1.269338e+08,1.201418e+08,1.173919e+08,1.127701e+08,4.467083e+09,8.732519e+07,4.154212e+09,8.598031e+07,9.000000

In [43]:
# Univarient Analysis 
# Compute dispersion parameters
numeric_cols = user_aggregation_cleaned.select_dtypes(include=[np.number]).columns
for column in numeric_cols:
    print(f'{column} - Variance: {user_aggregation_cleaned[column].var()}, Standard Deviation: {user_aggregation_cleaned[column].std()}')

MSISDN/Number - Variance: 9.409478767512696e+19, Standard Deviation: 9700246784.238377
Bearer Id - Variance: 0.5446260282125556, Standard Deviation: 0.7379878238918007
Dur. (ms) - Variance: 13446602075.002525, Standard Deviation: 115959.48462718574
Total DL (Bytes) - Variance: 1.9294807715689248e+17, Standard Deviation: 439258553.8801635
Total UL (Bytes) - Variance: 1091666927646768.0, Standard Deviation: 33040383.285409506
Social Media DL (Bytes) - Variance: 3212393169216.335, Standard Deviation: 1792315.0306841526
Social Media UL (Bytes) - Variance: 1084425499.6202745, Standard Deviation: 32930.61644762021
Google DL (Bytes) - Variance: 32984708937933.848, Standard Deviation: 5743231.576206365
Google UL (Bytes) - Variance: 4262090636159.521, Standard Deviation: 2064483.1401974494
Email DL (Bytes) - Variance: 3227678176834.2803, Standard Deviation: 1796574.0109537041
Email UL (Bytes) - Variance: 220151824339.2406, Standard Deviation: 469203.3933586165
Youtube DL (Bytes) - Variance: 136279051414479.19, Standard Deviation: 11673861.889472531
Youtube UL (Bytes) - Variance: 120967227939378.0, Standard Deviation: 10998510.260002397
Netflix DL (Bytes) - Variance: 136908278298457.47, Standard Deviation: 11700781.097792465
Netflix UL (Bytes) - Variance: 121161326098191.36, Standard Deviation: 11007330.561866095
Gaming DL (Bytes) - Variance: 1.7732182925413088e+17, Standard Deviation: 421095985.7967431
Gaming UL (Bytes) - Variance: 68832140310652.375, Standard Deviation: 8296513.744377959
Other DL (Bytes) - Variance: 1.7776131278779242e+17, Standard Deviation: 421617495.82742935
Other UL (Bytes) - Variance: 68171317140406.36, Standard Deviation: 8256592.344327432
Decile - Variance: 8.281071007117754, Standard Deviation: 2.877685008321403

In [44]:
import seaborn as sns
import matplotlib.pyplot as plt

# Plot histograms for each numerical column
for column in numeric_cols:
    plt.figure()
    sns.histplot(user_aggregation_cleaned[column], kde=True)
    plt.title(f'Distribution of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.show()

### Bivraiant Analysis

In [ ]:
# Analyze relationship between each application and Total DL + UL data
user_aggregation_cleaned['Total Data'] = user_aggregation_cleaned['Total DL (Bytes)'] + user_aggregation_cleaned['Total UL (Bytes)']

applications = [
    'Social Media DL (Bytes)', 'Google DL (Bytes)', 'Email DL (Bytes)',
    'Youtube DL (Bytes)', 'Netflix DL (Bytes)', 'Gaming DL (Bytes)', 'Other DL (Bytes)'
]

for app in applications:
    plt.figure()
    sns.scatterplot(x=user_aggregation_cleaned[app], y=user_aggregation_cleaned['Total Data'])
    plt.title(f'{app} vs Total Data')
    plt.xlabel(app)
    plt.ylabel('Total Data')
    plt.show()